import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'swiper/css';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simp Game Studio",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        sizes: "16x16",
        type: "image/png",
        url: '/Icon-192.png',
        href: '/Icon-192.png',
      },
      {
        media: '(prefers-color-scheme: dark)',
        sizes: "16x16",
        type: "image/png",
        url: '/Icon-192-dark.png',
        href: '/Icon-192-dark.png',
      },
 
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
